[global]
port = 1234
jwt_key = "n5LXiLeQ0UqaVwOSySIARzraSebDviRL1nLrNCWG1HM="
upload_dir = "/path/to/upload"
upload_size_limit = 1048576 # 1024 * 1024 1mb
upload_allowed_extension = "jpg,jpeg,png,gif,webp,md"
databases = {main = { url = "postgres://postgres:postgres@127.0.0.1:5438/aid"}}